# Generated by Django 5.0.4 on 2024-04-26 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet4you_app', '0003_alter_pet_id_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='favorited',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
