name: Testing
on: push

jobs:
  test_project:
    runs-on: ubuntu-latest
    env:
      TARGET_ENV: Dev
    steps:
      - name: Install dependencies
        run: |
          cd ..
          cd ..
          pip install -r requirements.txt
          npm ci

      - name: Run local server
        run: |
          python manage.py migrate
          python manage.py runserver &
          sleep 5
          npx cypress run    
      
      - name: Cleaning testing files
        run: |
          rm .env
          rm db.sqlite3
          rm cypress.config.js
          rm package-lock.json
          rm package.json
          rm -rf cypress
          rm -rf node_modules